substitutions:
  board: "esp32-poe"
  variant: "ESP32"
  flash_size: "4MB"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    mode: CLK_OUT
    pin: 17
  phy_addr: 0
  power_pin:
    number: GPIO12
    ignore_strapping_warning: true
